env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  experimentalObjectRestSpread: true
plugins:
  - react
rules: {
  'react/prop-types': off
}
